# * Should only be run on a trusted (and dedicated) server!
# * This script relies on 
#  - a private key in the gitlab_to_github_deploy_key env var
#  - a public key on github
#  - a public key (deploy) on gitlab

before_script:
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # annoyingly, there are a bunch of windows return characters in this env var (a gitlab bug)
  # extra annoyingly, a tmp file is needed - can't get a pipe to perl to work inside the ssh-add line
  - echo "$gitlab_to_github_deploy_key" | perl -pi -e 's/\r\n/\n/g' > ./deploykey
  # following line set up in the way it is to avoid an extra chmod step
  - ssh-add <(cat ./deploykey )
  # quick, get rid of it!
  - rm -f ./deploykey

types:
  - clean
  - build
  - test
  - deploy

clean_app:
  type: clean
  script: 
   - docker rm $(docker ps -a -q) || true
   - docker rmi $(docker images -q) || true
  
build_app:
  type: build
  script:
   - make -C bowtie/1.1.1/
   - make -C bowtie/1.1.2/
   - make -C bowtie2/2.2.9/
   - make -C bwa/0.7.15/
   - make -C eqtlbma/v1.3.1
   - make -C hmmer/3.b2

test_app:
  type: test
  script:
   - make -C bowtie/1.1.1/ test
   - make -C bowtie/1.1.2/ test
   - make -C bowtie2/2.2.9/ test
   - make -C bwa/0.7.15/ test
   - make -C eqtlbma/v1.3.1 test
   - make -C hmmer/3.b2 test

deploy_app:
  type: deploy
  script: 
   - echo "Force push to github disabled"
#   - git clone git@bigr:sacim/docker-bio && cd docker-bio && git push -f git@github.com:sglim2/docker-bio  master && cd .. && rm -rf docker-bio


